create table if not exists public.records (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  code text not null,
  detail text not null default '',
  contact text not null default '',
  amount bigint not null default 0,
  status text not null default 'Đang hoạt động',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists records_type_idx on public.records(type);
alter table public.records enable row level security;
