"use client";
import { FormEvent, useMemo, useState } from "react";

type RecordItem={id:number;type:string;name:string;code:string;detail:string;contact:string;amount:number;status:string};
type Draft=Omit<RecordItem,"id">;
const modules=[["Tổng quan","⌂"],["Học sinh","♟"],["Giáo viên","♜"],["Lớp học","▣"],["Lịch học","□"],["Điểm danh","✓"],["Học phí","₫"],["Kết quả","▥"]];
const labels:Record<string,[string,string,string,string,string]>={
 "Học sinh":["Tên học sinh","Mã học sinh","Lớp / ngày sinh","SĐT phụ huynh","Trạng thái"],
 "Giáo viên":["Tên giáo viên","Mã giáo viên","Môn giảng dạy","Điện thoại","Trạng thái"],
 "Lớp học":["Tên lớp","Mã lớp","Môn · Phòng · Lịch","Giáo viên","Trạng thái"],
 "Lịch học":["Tên buổi học","Mã lịch","Thời gian · Phòng","Giáo viên","Trạng thái"],
 "Điểm danh":["Học sinh","Mã điểm danh","Ngày · Lớp","Ghi chú","Trạng thái"],
 "Học phí":["Học sinh","Mã phiếu","Kỳ học phí · Hạn đóng","Liên hệ","Trạng thái"],
 "Kết quả":["Học sinh","Mã kết quả","Môn · Điểm · Học kỳ","Nhận xét","Trạng thái"]};
const empty=(type:string):Draft=>({type,name:"",code:"",detail:"",contact:"",amount:0,status:"Đang hoạt động"});

export default function Home(){
 const [active,setActive]=useState("Tổng quan"),[rows,setRows]=useState<RecordItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<number|null>(null),[draft,setDraft]=useState<Draft>(empty("Học sinh")),[toast,setToast]=useState(""),[menu,setMenu]=useState(false);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const load=async(type:string)=>{if(type==="Tổng quan")return;setLoading(true);setError("");try{const r=await fetch(`/api/records?type=${encodeURIComponent(type)}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.records)}catch{setError("Không thể tải dữ liệu. Vui lòng thử lại.")}finally{setLoading(false)}};
 const choose=(name:string)=>{setActive(name);setQuery("");setMenu(false);void load(name)};
 const openNew=()=>{setEditing(null);setDraft(empty(active));setModal(true)};
 const openEdit=(r:RecordItem)=>{setEditing(r.id);setDraft({type:r.type,name:r.name,code:r.code,detail:r.detail,contact:r.contact,amount:r.amount,status:r.status});setModal(true)};
 const save=async(e:FormEvent)=>{e.preventDefault();setError("");try{const res=await fetch("/api/records",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...draft,id:editing}:draft)});const j=await res.json();if(!res.ok)throw new Error(j.error);setModal(false);notify(editing?"Đã cập nhật dữ liệu":"Đã thêm dữ liệu mới");await load(active)}catch(e){setError(e instanceof Error?e.message:"Không thể lưu dữ liệu")}};
 const remove=async(r:RecordItem)=>{if(!confirm(`Xóa “${r.name}”?`))return;const res=await fetch("/api/records",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id,type:r.type})});if(res.ok){notify("Đã xóa dữ liệu");load(active)}else notify("Không thể xóa dữ liệu")};
 const visible=useMemo(()=>rows.filter(r=>`${r.name} ${r.code} ${r.detail}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 return <main className="app-shell">
  <aside className={menu?"sidebar open":"sidebar"}><div className="brand"><span className="brandmark">✦</span>EduCenter</div><nav>{modules.map(([n,i])=><button key={n} className={active===n?"nav-item active":"nav-item"} onClick={()=>choose(n)}><span className="nav-icon">{i}</span>{n}</button>)}</nav><div className="help-card"><div className="help-icon">✓</div><div><strong>Dữ liệu an toàn</strong><small>Tự động lưu trên hệ thống</small></div><button onClick={()=>notify("Hệ thống đang hoạt động ổn định")}>Kiểm tra <span>→</span></button></div></aside>
  <section className="workspace"><header className="topbar"><button className="menu-btn" onClick={()=>setMenu(!menu)}>☰</button><div><p className="eyebrow">TRUNG TÂM ĐÀO TẠO</p><h1>{active==="Tổng quan"?"Chào buổi sáng, Thầy Minh":`Quản lý ${active.toLowerCase()}`}</h1></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo tên, mã..." /></label><button className="icon-btn" onClick={()=>notify("Không có thông báo mới")}>♢</button><button className="avatar">TM</button></header>
  <div className="content">{active==="Tổng quan"?<Dashboard onOpen={choose}/>:<section className="module-page"><div className="module-toolbar"><div><h2>{active}</h2><p>Quản lý, tra cứu và cập nhật dữ liệu {active.toLowerCase()}</p></div><button className="primary" onClick={openNew}>＋ Thêm mới</button></div><div className="module-stats"><Mini value={String(rows.length)} label="Tổng hồ sơ"/><Mini value={String(rows.filter(r=>!r.status.includes("Ngừng")&&!r.status.includes("Vắng")&&!r.status.includes("Quá hạn")).length)} label="Đang hoạt động"/><Mini value={String(rows.filter(r=>r.status.includes("Ngừng")||r.status.includes("Vắng")||r.status.includes("Quá hạn")).length)} label="Cần xử lý"/></div><div className="card data-card">{error&&<div className="alert">{error}<button onClick={()=>load(active)}>Thử lại</button></div>}{loading?<div className="loading">Đang tải dữ liệu…</div>:visible.length?<div className="table-wrap"><table><thead><tr><th>{labels[active][0]}</th><th>{labels[active][1]}</th><th>{labels[active][2]}</th><th>{labels[active][3]}</th>{active==="Học phí"&&<th>Số tiền</th>}<th>{labels[active][4]}</th><th>Thao tác</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><span className="student"><em>{r.name.split(" ").slice(-1)[0]?.[0]||"E"}</em><b>{r.name}</b></span></td><td><code>{r.code}</code></td><td>{r.detail||"—"}</td><td>{r.contact||"—"}</td>{active==="Học phí"&&<td>{r.amount.toLocaleString("vi-VN")} ₫</td>}<td><span className={r.status.includes("Quá")||r.status.includes("Vắng")?"fee-status late":"fee-status ok"}>{r.status}</span></td><td><div className="row-actions"><button onClick={()=>openEdit(r)}>Sửa</button><button className="danger" onClick={()=>remove(r)}>Xóa</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><span>▤</span><h3>Chưa có dữ liệu {active.toLowerCase()}</h3><p>Hãy thêm hồ sơ đầu tiên để bắt đầu quản lý.</p><button className="primary" onClick={openNew}>＋ Thêm mới</button></div>}</div></section>}</div></section>
  {menu&&<button className="scrim" onClick={()=>setMenu(false)}/>} {toast&&<div className="toast">✓ {toast}</div>}
  {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><small>{editing?"CHỈNH SỬA":"THÊM MỚI"}</small><h2>{active}</h2></div><button onClick={()=>setModal(false)}>×</button></header><form onSubmit={save}><label>{labels[active][0]}<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{labels[active][1]}<input required value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></label><label>{labels[active][2]}<input value={draft.detail} onChange={e=>setDraft({...draft,detail:e.target.value})}/></label><label>{labels[active][3]}<input value={draft.contact} onChange={e=>setDraft({...draft,contact:e.target.value})}/></label>{active==="Học phí"&&<label>Số tiền (VNĐ)<input type="number" min="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label>}<label>{labels[active][4]}<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Đang hoạt động</option><option>Đã hoàn thành</option><option>Chờ xử lý</option><option>Vắng mặt</option><option>Quá hạn</option><option>Ngừng học</option></select></label>{error&&<div className="alert">{error}</div>}<footer><button type="button" onClick={()=>setModal(false)}>Hủy</button><button className="primary" type="submit">{editing?"Lưu thay đổi":"Thêm dữ liệu"}</button></footer></form></div></div>}
 </main>
}
function Mini({value,label}:{value:string,label:string}){return <div className="mini-stat"><strong>{value}</strong><span>{label}</span></div>}
function Dashboard({onOpen}:{onOpen:(s:string)=>void}){const cards=[["1.248","Học sinh","♟"],["42","Giáo viên","♜"],["36","Lớp đang học","▣"],["428,5 triệu","Doanh thu tháng","₫"]];return <><div className="welcome-row"><div><h2>Tổng quan hoạt động</h2><p>Chọn một mô-đun để quản lý dữ liệu thực tế</p></div></div><section className="kpi-grid">{cards.map(([v,l,i])=><button className="kpi card" key={l} onClick={()=>onOpen(l==="Lớp đang học"?"Lớp học":l==="Doanh thu tháng"?"Học phí":l)}><span className="kpi-icon green">{i}</span><div><strong>{v}</strong><p>{l}</p></div><small>Mở quản lý <span>→</span></small></button>)}</section><section className="quick-grid"><article className="card quick-card"><h3>Công việc hôm nay</h3>{[["Điểm danh lớp Toán 8A","07:30"],["Thu học phí lớp 10B","09:15"],["Nhập kết quả Vật lý 12","14:00"]].map(x=><div className="task" key={x[0]}><i></i><span>{x[0]}</span><time>{x[1]}</time></div>)}</article><article className="card quick-card"><h3>Truy cập nhanh</h3><div className="quick-buttons">{["Học sinh","Lớp học","Điểm danh","Học phí"].map(n=><button key={n} onClick={()=>onOpen(n)}>＋ {n}</button>)}</div></article></section></>}
