"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useMemo, useState } from "react";

type RecordItem={id:number;type:string;name:string;code:string;detail:string;contact:string;amount:number;status:string};
type Draft=Omit<RecordItem,"id">;
type AuthState={accessToken:string;refreshToken:string;email:string};
const modules=[["Tổng quan","⌂"],["Học sinh","♟"],["Giáo viên","♜"],["Lớp học","▣"],["Lịch học","□"],["Điểm danh","✓"],["Học phí","₫"],["Kết quả","▥"]];
const labels:Record<string,[string,string,string,string,string]>={"Học sinh":["Tên học sinh","Mã học sinh","Lớp / ngày sinh","SĐT phụ huynh","Trạng thái"],"Giáo viên":["Tên giáo viên","Mã giáo viên","Môn giảng dạy","Điện thoại","Trạng thái"],"Lớp học":["Tên lớp","Mã lớp","Môn · Phòng · Lịch","Giáo viên","Trạng thái"],"Lịch học":["Tên buổi học","Mã lịch","Thời gian · Phòng","Giáo viên","Trạng thái"],"Điểm danh":["Học sinh","Mã điểm danh","Ngày · Lớp","Ghi chú","Trạng thái"],"Học phí":["Học sinh","Mã phiếu","Kỳ học phí · Hạn đóng","Liên hệ","Trạng thái"],"Kết quả":["Học sinh","Mã kết quả","Môn · Điểm · Học kỳ","Nhận xét","Trạng thái"]};
const empty=(type:string):Draft=>({type,name:"",code:"",detail:"",contact:"",amount:0,status:"Đang hoạt động"});
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL??"",anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";

export default function Home(){
 const [auth,setAuth]=useState<AuthState|null>(null),[authLoading,setAuthLoading]=useState(true),[active,setActive]=useState("Tổng quan"),[rows,setRows]=useState<RecordItem[]>([]),[allRows,setAllRows]=useState<RecordItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<number|null>(null),[draft,setDraft]=useState<Draft>(empty("Học sinh")),[toast,setToast]=useState(""),[menu,setMenu]=useState(false);
 useEffect(()=>{let cancelled=false;const finish=(a:AuthState|null)=>{if(!cancelled){setAuth(a);setAuthLoading(false);if(a)void loadAll(a.accessToken)}};const hash=new URLSearchParams(window.location.hash.slice(1)),token=hash.get("access_token"),refresh=hash.get("refresh_token")??"";if(token){history.replaceState(null,"",window.location.pathname);fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:anonKey,Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(u=>{const a={accessToken:token,refreshToken:refresh,email:u.email??"Tài khoản Gmail"};localStorage.setItem("educenter_auth",JSON.stringify(a));finish(a)}).catch(()=>finish(null));return()=>{cancelled=true}}const saved=localStorage.getItem("educenter_auth");if(!saved){finish(null);return()=>{cancelled=true}}try{const a=JSON.parse(saved) as AuthState;fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:anonKey,Authorization:`Bearer ${a.accessToken}`}}).then(r=>r.ok?r.json():Promise.reject()).then(u=>finish({...a,email:u.email??a.email})).catch(()=>{localStorage.removeItem("educenter_auth");finish(null)})}catch{finish(null)}return()=>{cancelled=true}},[]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const apiHeaders=(json=false)=>({...json?{"Content-Type":"application/json"}:{},Authorization:`Bearer ${auth?.accessToken??""}`});
 const loadAll=async(token=auth?.accessToken??"")=>{try{const r=await fetch("/api/records",{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(r.ok)setAllRows(j.records)}catch{}};
 const load=async(type:string)=>{if(type==="Tổng quan"){await loadAll();return}setLoading(true);setError("");try{const r=await fetch(`/api/records?type=${encodeURIComponent(type)}`,{headers:apiHeaders()});const j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.records)}catch{setError("Không thể tải dữ liệu. Vui lòng thử lại.")}finally{setLoading(false)}};
 const choose=(name:string)=>{setActive(name);setQuery("");setMenu(false);void load(name)};
 const login=()=>{if(!supabaseUrl||!anonKey){setError("Chưa cấu hình đăng nhập Supabase trên Vercel");return}window.location.href=`${supabaseUrl}/auth/v1/authorize?provider=google&redirect_to=${encodeURIComponent(window.location.origin)}`};
 const logout=async()=>{if(auth)await fetch(`${supabaseUrl}/auth/v1/logout`,{method:"POST",headers:{apikey:anonKey,Authorization:`Bearer ${auth.accessToken}`}}).catch(()=>null);localStorage.removeItem("educenter_auth");setAuth(null);setAllRows([]);setRows([])};
 const openNew=()=>{setEditing(null);setDraft(empty(active));setModal(true)};
 const openEdit=(r:RecordItem)=>{setEditing(r.id);setDraft({type:r.type,name:r.name,code:r.code,detail:r.detail,contact:r.contact,amount:r.amount,status:r.status});setModal(true)};
 const save=async(e:FormEvent)=>{e.preventDefault();setError("");try{const res=await fetch("/api/records",{method:editing?"PUT":"POST",headers:apiHeaders(true),body:JSON.stringify(editing?{...draft,id:editing}:draft)});const j=await res.json();if(!res.ok)throw new Error(j.error);setModal(false);notify(editing?"Đã cập nhật dữ liệu":"Đã thêm dữ liệu mới");await Promise.all([load(active),loadAll()])}catch(e){setError(e instanceof Error?e.message:"Không thể lưu dữ liệu")}};
 const remove=async(r:RecordItem)=>{if(!confirm(`Xóa “${r.name}”?`))return;const res=await fetch("/api/records",{method:"DELETE",headers:apiHeaders(true),body:JSON.stringify({id:r.id,type:r.type})});if(res.ok){notify("Đã xóa dữ liệu");await Promise.all([load(active),loadAll()])}else notify("Không thể xóa dữ liệu")};
 const visible=useMemo(()=>rows.filter(r=>`${r.name} ${r.code} ${r.detail}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 if(authLoading)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",fontFamily:"system-ui",color:"#176b57"}}>Đang kiểm tra đăng nhập…</div>;
 if(!auth)return <AuthScreen onLogin={login} error={error}/>;
 return <main className="app-shell">
  <aside className={menu?"sidebar open":"sidebar"}><div className="brand"><span className="brandmark">✦</span>EduCenter</div><nav>{modules.map(([n,i])=><button key={n} className={active===n?"nav-item active":"nav-item"} onClick={()=>choose(n)}><span className="nav-icon">{i}</span>{n}</button>)}</nav><div className="help-card"><div className="help-icon">✓</div><div><strong>Dữ liệu thực</strong><small>Đồng bộ theo tài khoản</small></div><button onClick={logout}>Đăng xuất <span>→</span></button></div></aside>
  <section className="workspace"><header className="topbar"><button className="menu-btn" onClick={()=>setMenu(!menu)}>☰</button><div><p className="eyebrow">TRUNG TÂM ĐÀO TẠO</p><h1>{active==="Tổng quan"?`Xin chào, ${auth.email.split("@")[0]}`:`Quản lý ${active.toLowerCase()}`}</h1></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo tên, mã..."/></label><button className="avatar" title={auth.email}>{auth.email.slice(0,2).toUpperCase()}</button></header>
  <div className="content">{active==="Tổng quan"?<Dashboard onOpen={choose} rows={allRows}/>:<section className="module-page"><div className="module-toolbar"><div><h2>{active}</h2><p>Quản lý, tra cứu và cập nhật dữ liệu {active.toLowerCase()}</p></div><button className="primary" onClick={openNew}>＋ Thêm mới</button></div><div className="module-stats"><Mini value={String(rows.length)} label="Tổng hồ sơ"/><Mini value={String(rows.filter(r=>!r.status.includes("Ngừng")&&!r.status.includes("Vắng")&&!r.status.includes("Quá hạn")).length)} label="Đang hoạt động"/><Mini value={String(rows.filter(r=>r.status.includes("Ngừng")||r.status.includes("Vắng")||r.status.includes("Quá hạn")).length)} label="Cần xử lý"/></div><div className="card data-card">{error&&<div className="alert">{error}<button onClick={()=>load(active)}>Thử lại</button></div>}{loading?<div className="loading">Đang tải dữ liệu…</div>:visible.length?<div className="table-wrap"><table><thead><tr><th>{labels[active][0]}</th><th>{labels[active][1]}</th><th>{labels[active][2]}</th><th>{labels[active][3]}</th>{active==="Học phí"&&<th>Số tiền</th>}<th>{labels[active][4]}</th><th>Thao tác</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><span className="student"><em>{r.name.split(" ").slice(-1)[0]?.[0]||"E"}</em><b>{r.name}</b></span></td><td><code>{r.code}</code></td><td>{r.detail||"—"}</td><td>{r.contact||"—"}</td>{active==="Học phí"&&<td>{r.amount.toLocaleString("vi-VN")} ₫</td>}<td><span className={r.status.includes("Quá")||r.status.includes("Vắng")?"fee-status late":"fee-status ok"}>{r.status}</span></td><td><div className="row-actions"><button onClick={()=>openEdit(r)}>Sửa</button><button className="danger" onClick={()=>remove(r)}>Xóa</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><span>▤</span><h3>Chưa có dữ liệu {active.toLowerCase()}</h3><p>Hãy thêm hồ sơ đầu tiên để bắt đầu quản lý.</p><button className="primary" onClick={openNew}>＋ Thêm mới</button></div>}</div></section>}</div></section>
  {menu&&<button className="scrim" onClick={()=>setMenu(false)}/>} {toast&&<div className="toast">✓ {toast}</div>}
  {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><small>{editing?"CHỈNH SỬA":"THÊM MỚI"}</small><h2>{active}</h2></div><button onClick={()=>setModal(false)}>×</button></header><form onSubmit={save}><label>{labels[active][0]}<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{labels[active][1]}<input required value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></label><label>{labels[active][2]}<input value={draft.detail} onChange={e=>setDraft({...draft,detail:e.target.value})}/></label><label>{labels[active][3]}<input value={draft.contact} onChange={e=>setDraft({...draft,contact:e.target.value})}/></label>{active==="Học phí"&&<label>Số tiền (VNĐ)<input type="number" min="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label>}<label>{labels[active][4]}<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Đang hoạt động</option><option>Đã hoàn thành</option><option>Chờ xử lý</option><option>Vắng mặt</option><option>Quá hạn</option><option>Ngừng học</option></select></label>{error&&<div className="alert">{error}</div>}<footer><button type="button" onClick={()=>setModal(false)}>Hủy</button><button className="primary" type="submit">{editing?"Lưu thay đổi":"Thêm dữ liệu"}</button></footer></form></div></div>}
 </main>
}
function Mini({value,label}:{value:string,label:string}){return <div className="mini-stat"><strong>{value}</strong><span>{label}</span></div>}
function Dashboard({onOpen,rows}:{onOpen:(s:string)=>void;rows:RecordItem[]}){const count=(t:string)=>rows.filter(r=>r.type===t).length,revenue=rows.filter(r=>r.type==="Học phí").reduce((s,r)=>s+r.amount,0),cards=[[String(count("Học sinh")),"Học sinh","♟"],[String(count("Giáo viên")),"Giáo viên","♜"],[String(count("Lớp học")),"Lớp học","▣"],[`${revenue.toLocaleString("vi-VN")} ₫`,"Học phí ghi nhận","₫"]],tasks=rows.filter(r=>["Lịch học","Điểm danh","Học phí","Kết quả"].includes(r.type)).slice(0,3);return <><div className="welcome-row"><div><h2>Tổng quan hoạt động</h2><p>Số liệu được tổng hợp trực tiếp từ dữ liệu đã lưu</p></div></div><section className="kpi-grid">{cards.map(([v,l,i])=><button className="kpi card" key={l} onClick={()=>onOpen(l==="Học phí ghi nhận"?"Học phí":l)}><span className="kpi-icon green">{i}</span><div><strong>{v}</strong><p>{l}</p></div><small>Mở quản lý <span>→</span></small></button>)}</section><section className="quick-grid"><article className="card quick-card"><h3>Công việc gần nhất</h3>{tasks.length?tasks.map(x=><div className="task" key={x.id}><i></i><span>{x.name}</span><time>{x.type}</time></div>):<div className="empty-state" style={{minHeight:160}}><p>Chưa có công việc hoặc lịch học.</p></div>}</article><article className="card quick-card"><h3>Truy cập nhanh</h3><div className="quick-buttons">{["Học sinh","Lớp học","Điểm danh","Học phí"].map(n=><button key={n} onClick={()=>onOpen(n)}>＋ {n}</button>)}</div></article></section></>}
function AuthScreen({onLogin,error}:{onLogin:()=>void;error:string}){return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f7f4ec",fontFamily:"system-ui",padding:20}}><section style={{width:"min(440px,100%)",background:"white",border:"1px solid #e7e3d9",borderRadius:24,padding:36,boxShadow:"0 20px 60px #174b3e18",textAlign:"center"}}><div style={{width:64,height:64,borderRadius:20,margin:"0 auto 18px",display:"grid",placeItems:"center",background:"#0f8a6a",color:"white",fontSize:30}}>✦</div><h1 style={{margin:0,color:"#174b3e"}}>EduCenter</h1><p style={{color:"#73827c",lineHeight:1.6}}>Đăng ký hoặc đăng nhập để quản lý dữ liệu trường học an toàn.</p><button onClick={onLogin} style={{width:"100%",border:"1px solid #d8ddd9",borderRadius:12,padding:"13px 16px",background:"white",fontWeight:700,cursor:"pointer",fontSize:15}}>G&nbsp;&nbsp; Tiếp tục với Google / Gmail</button>{error&&<p style={{color:"#b54038",fontSize:13}}>{error}</p>}<small style={{display:"block",marginTop:18,color:"#8a9691"}}>Lần đăng nhập đầu tiên sẽ tự động tạo tài khoản.</small></section></main>}
