const allowed = new Set(["Học sinh","Giáo viên","Lớp học","Lịch học","Điểm danh","Học phí","Kết quả"]);
const clean=(v:unknown,max=160)=>String(v??"").trim().slice(0,max);
const config=()=>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Chưa cấu hình Supabase");return{url,key}};
const headers=(key:string)=>({apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=representation"});
function values(body:Record<string,unknown>){const type=clean(body.type,30),name=clean(body.name),code=clean(body.code,40);if(!allowed.has(type)||!name||!code)throw new Error("Tên, mã và loại dữ liệu là bắt buộc");return{type,name,code,detail:clean(body.detail,240),contact:clean(body.contact,100),amount:Math.max(0,Math.round(Number(body.amount)||0)),status:clean(body.status,40)||"Đang hoạt động",updated_at:new Date().toISOString()}}
export async function GET(req:Request){try{const{url,key}=config(),type=new URL(req.url).searchParams.get("type")??"";if(!allowed.has(type))return Response.json({records:[]});const r=await fetch(`${url}/rest/v1/records?type=eq.${encodeURIComponent(type)}&select=*&order=updated_at.desc`,{headers:headers(key),cache:"no-store"});if(!r.ok)throw new Error();return Response.json({records:await r.json()})}catch(e){return Response.json({error:e instanceof Error?e.message:"Không thể tải dữ liệu"},{status:500})}}
export async function POST(req:Request){try{const{url,key}=config(),v=values(await req.json());const r=await fetch(`${url}/rest/v1/records`,{method:"POST",headers:headers(key),body:JSON.stringify(v)});const data=await r.json();if(!r.ok)throw new Error(data.message||"Không thể thêm dữ liệu");return Response.json({record:data[0]},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"Dữ liệu không hợp lệ"},{status:400})}}
export async function PUT(req:Request){try{const{url,key}=config(),body=await req.json() as Record<string,unknown>,id=Number(body.id),v=values(body);if(!Number.isInteger(id))throw new Error("ID không hợp lệ");const r=await fetch(`${url}/rest/v1/records?id=eq.${id}&type=eq.${encodeURIComponent(v.type)}`,{method:"PATCH",headers:headers(key),body:JSON.stringify(v)});const data=await r.json();if(!r.ok||!data[0])throw new Error("Không tìm thấy dữ liệu");return Response.json({record:data[0]})}catch(e){return Response.json({error:e instanceof Error?e.message:"Không thể cập nhật"},{status:400})}}
export async function DELETE(req:Request){try{const{url,key}=config(),body=await req.json() as {id?:number,type?:string},id=Number(body.id),type=clean(body.type,30);if(!Number.isInteger(id)||!allowed.has(type))throw new Error();const r=await fetch(`${url}/rest/v1/records?id=eq.${id}&type=eq.${encodeURIComponent(type)}`,{method:"DELETE",headers:headers(key)});if(!r.ok)throw new Error();return Response.json({ok:true})}catch{return Response.json({error:"Không thể xóa dữ liệu"},{status:400})}}
